# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProj2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FlexLayout'
  pod 'PinLayout' 
  pod 'Then'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.0.0'

  # Pods for TestProj2

  target 'TestProj2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestProj2UITests' do
    # Pods for testing
  end

end
