# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoordinatorPrx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoordinatorPrx
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'RxFlow'
    pod 'Then'
    pod 'SnapKit', '~> 5.0.0'
end
