# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GIFinTextViewPrx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GIFinTextViewPrx
  pod 'FlexLayout'
  pod 'PinLayout' 
  pod 'Then'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'Streamoji'
  pod 'Differ'
  pod 'DifferenceKit'
end
